---
- name: This sets up an httpd webserver
  hosts: all
  tasks:
  - name: Install apache & firewalld packages 
    yum:
      name:
        - httpd
        - firewalld
      state: present
  - name: ensure httpd & firewalld is running
    service:
      name: 
        - httpd
        - firewalld
      state: started
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
